@startuml

|Пользователь|

start

:Выбрать комнату;

|Система|

:Проверить доступность комнаты;

if (Комната свободна?) then (Да)
    
    :Создать бронирование;
    
    fork
        :Сохранить в БД;
    fork again
        :Уведомить пользователя;
    fork again
        :Записать аудит;
    end fork


else (Нет)
    |Система|
    :Показать сообщение об ошибке;

endif

stop

@enduml