@startuml
autoactivate on

actor User

participant "Booking Service" as BS
participant "Identity Provider" as IdP
database "PostgreSQL" as DB

User -> BS : authenticate()

BS -> IdP : validateCredentials()

alt Credentials valid

    IdP --> BS : accessToken

    BS -> DB : saveUserSession()

    DB --> BS : saveResult

    BS --> User : authenticationSuccess

else Credentials invalid

    IdP --> BS : authenticationFailed

    BS --> User : authenticationError

end

@enduml