@startuml
autoactivate on

actor User

participant "Booking Service" as BS
database "PostgreSQL" as DB
queue "RabbitMQ" as Rabbit
participant "Email Service" as ES

User -> BS : createBooking()

BS -> DB : getRoomAvailability()

alt Room available

    DB --> BS : roomAvailability

    BS -> DB : saveBooking()

    DB --> BS : bookingSaved

else Room unavailable

    DB --> BS : roomAvailability

end

BS ->> Rabbit : publishBookingStatusChanged()

BS --> User : bookingResult

autoactivate off

Rabbit ->> ES : consumeBookingStatusChanged()

activate ES
ES -> ES : sendEmailNotification()
deactivate ES

@enduml