@startuml

title Activity Diagram Возврат ключевого носителя электронной подписи

|Пользователь|

start

:Завершить работу с использованием ключа ЭП;
:Инициировать возврат ключевого носителя;

|Ответственный за хранение|

:Принять ключевой носитель;
:Зарегистрировать возврат в журнале учета;

|Пользователь|
:Расписаться в возврате ключевого носителя;

|Ответственный за хранение|
:Поместить носитель в место хранения;


|Ответственный за хранение|

:Поместить носитель на ответственное хранение;

stop


@enduml