@startuml

title AD-03. Обработка инцидента компрометации ключа электронной подписи

|Пользователь|

start

:Выявить признаки компрометации;
:Немедленно прекратить использование ключа;
:Уведомить ответственного за хранение;
:Уведомить ИТ-подразделение;

|ИТ-подразделение|
 
:Зарегистрировать инцидент;
:Проверить обстоятельства;

if (Компрометация подтверждена?) then (Да)
 
:Инициировать отзыв сертификата;

|Информационная безопасность|

:Провести расследование;
:Определить причины инцидента;
:Подготовить рекомендации;

|ИТ-подразделение|

:Выпустить новый сертификат;
:Передать информацию ответственному за хранение;

stop

else (Нет)

:Закрыть инцидент;
:Проинформировать инициатора;

stop

endif

@enduml