@startuml

title Activity Diagram Выдача ключевого носителя электронной подписи

|Пользователь|

start

:Запрос ключевого носителя ЭЦП;

|Ответственный за хранение|

:Проверить полномочия;

if (Полномочия подтверждены?) then (Да)
    
    :Регистрация выдачи ключевого носителя ЭЦП;
    :Выдача ключевого носителя ЭЦП;
    |Пользователь|
    :Подтверждение получения ключевого носителя ЭЦП;

|Ответственный за хранение|
else (Нет)
    :Отказ в выдаче ключевого носителя ЭЦП;


endif

stop

@enduml