US-01 Регистрация нового обращения
Описание
**Как** Оператор центра приема заявок,
**Я хочу** зарегистрировать новое обращение клиента в системе,
**Чтобы** заявка не потерялась, был соблюден SLA ответа и юрист мог начать работу.
### Примечания
1. В форме должны быть поля: Наименование, Телефон, Эл. почта, Адрес, Доверенное лицо.
2. Проверка дубликата клиента осуществляется по телефону.
### Критерии приемки (Acceptance Criteria)

- [AC-1] Можно внести контактные данные клиента.
- [AC-2] Можно указать приоритетный способ связи с клиентом.
- [AC-3] Можно внести краткую информацию по обращению.
- [AC-4] Можно определить, есть ли клиент уже в базе.
- [AC-5] Поля «Телефон», «ФИО», «Тема обращения» — обязательные. Кнопка «Сохранить» неактивна, пока не заполнены.
- [AC-6] Телефон маскируется в формате +7 (___) _**-**-__. Ввод букв блокируется.
- [AC-7] Если телефон найден в базе → показать модальное окно с данными существующего клиента.


### Сценарии приемки
**Сценарий 1: Клиент отсутствует в базе**
Дано клиент отсутствует в базе
Когда оператор создает новое обращение
И вносит контактные данные клиента
И выбирает приоритетный способ связи
И указывает информацию по обращению
Тогда создается карточка нового обращения

**Сценарий 2: Клиент есть в базе**
Дано клиент есть в базе
Когда оператор вносит данные клиента
И система предлагает выбрать существующего клиента
И оператор выбирает клиента из списка
Тогда создается карточка нового обращения, привязанная к существующему клиенту