@startuml

left to right direction

actor Employee
actor Administrator
actor UserSystem
actor Manager

Employee -|> UserSystem
Administrator -|> UserSystem
Manager -|> UserSystem

rectangle "Meeting Room Booking System" {

    usecase "Найти свободную комнату" as UC1
    usecase "Забронировать комнату" as UC2
    usecase "Отменить бронирование" as UC3
    usecase "Управление комнатами" as UC4
    usecase "Проверить доступность комнаты" as UC5
    usecase "Добавить участников встречи" as UC6



    UC6 .> UC2 : <<extend>>
    UC1 .> UC5 : <<include>>


}

UserSystem --> UC1
UserSystem --> UC2
UserSystem --> UC3

Administrator --> UC4

@enduml