@startuml
autoactivate on

actor User

participant "Booking Service" as BS
database "PostgreSQL" as DB
queue "RabbitMQ" as Rabbit
participant "Email Service" as ES

User -> BS : СоздатьБронирование()

BS -> DB : ПроверитьДоступностьКомнаты()

alt Комната доступна

    DB --> BS : СтатусДоступности

    BS -> DB : СохранитьБронирование()

    DB --> BS : РезультатСохранения

    BS ->> Rabbit : ОпубликоватьСтатусБронирования()

    BS --> User : БронированиеУспешно

else Комната недоступна

    DB --> BS : СтатусДоступности

    BS ->> Rabbit : ОпубликоватьСтатусБронирования()

    BS --> User : ОтказВБронировании

end

autoactivate off

Rabbit ->> ES : ОбработатьСтатусБронирования()

activate ES
ES -> ES : ОтправитьEmailУведомление()
deactivate ES

@enduml