@startuml
autoactivate on

actor User

participant "Booking Service" as BS
database "PostgreSQL" as DB

User -> BS : НайтиСвободныеКомнаты()

BS -> DB : ПолучитьСписокСвободныхКомнат()

DB --> BS : СписокСвободныхКомнат

alt Свободные комнаты найдены

    BS --> User : СписокСвободныхКомнат

else Свободные комнаты отсутствуют

    BS --> User : СвободныеКомнатыОтсутствуют

end

@enduml